### ISSUE TITLE
Needs to fail gracefully

### ISSUE THREAD

**Issue by mkbowman** [UA-EPR-Lab/ENDOR#5]
Just tried processing an old ENDOR spectrum where Bruker did not write the B0VL, so things crashed when it couldn't return a value of that parameter.
Two possibilities: return no value found and check for it downstream or popup window to allow manual entry.

**Comment by jt-bama** [comment]
I pushed an update with an exception value in it, what should happen with an error in pulling bovl is a prompt will come up in the spyder command window asking you to manually input the field value.

Would you attach the file that is causing this error in case my solution does not work?

Once Molly and I get our heads together on the GUI implementation, this can be a window that pops up separate and prompts for window-level input, rather than command-line input

**Comment by jt-bama** [comment]
fixed to a pop-up tkinter window, not command-level anymore

**Comment by jt-bama** [comment]
closed
